spring.application.name=logap_api
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

# Prod
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
app.cors.origins=http://localhost:5173,https://meu-app-producao.com